import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Toast from "@/components/Toast";
import Nav from "@/components/Nav/Nav";
import Footer from "@/components/footer/Footer";

const interFont = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "E-Commerce Nextjs 15",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interFont.className} antialiased bg-background text-black`}
      >
        <Nav />
        {children}
        <Footer />
        <Toast />
      </body>
    </html>
  );
}
